<?php

namespace GG\UserBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository{

	public function findByOrder($order){
		$qb = $this->createQueryBuilder('a');
		$qb
			->where('a.order = :order')
			->setParameter('order', $order)
		;
	    
		return $qb
		    ->getQuery()
		    ->getResult()
	  ;

	}
}
