<?php

namespace GG\UserBundle\Repository;

/**
 * Identifiants_URepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Identifiants_URepository extends \Doctrine\ORM\EntityRepository
{
}
