<?php

namespace GG\UserBundle\Repository;

/**
 * UsagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsagerRepository extends \Doctrine\ORM\EntityRepository
{
}
