<?php

namespace GG\PaiementBundle\Repository;

/**
 * OrderPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderPaymentRepository extends \Doctrine\ORM\EntityRepository{
	
}
