<?php

namespace GG\BoutiqueBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository{
	public function findByCategorie($categorie){
		$qb = $this->createQueryBuilder('a');
		$qb
			->where('a.categorie = :categorie')
			->setParameter('categorie', $categorie)
		;
	    
		return $qb
		    ->getQuery()
		    ->getResult()
	  ;

	}
}
