<?php

namespace GG\BoutiqueBundle\Repository;

/**
 * DisponibilitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibilitesRepository extends \Doctrine\ORM\EntityRepository{

	public function findBase(){
		$qb = $this->createQueryBuilder('a');
		$qb
			->andWhere('a.reserved = :non')
			->setParameter('non', '0')
			->andWhere('a.valide = :oui')
			->setParameter('oui', '1')
		;
	    
		return $qb
		    ->getQuery()
		    ->getResult()
	  ;

	}

	public function findReserved(){
		$qb = $this->createQueryBuilder('a');
		$qb
			->andWhere('a.reserved = :oui')
			->andWhere('a.valide = :oui')
			->setParameter('oui', '1')
		;
	    
		return $qb
		    ->getQuery()
		    ->getResult()
	  ;

	}
}
