<?php

namespace GG\BoutiqueBundle\Repository;

/**
 * IdentifiantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentifiantsRepository extends \Doctrine\ORM\EntityRepository
{
	public function myFindAll($email, $password){
	    $queryBuilder = $this->createQueryBuilder('a');
	    $queryBuilder->where('a.email = :email')
       ->setParameter('email', $email);
	    // On récupère la Query à partir du QueryBuilder
	    $query = $queryBuilder->getQuery();

	    // On récupère les résultats à partir de la Query
	    $results = $query->getArrayResult();
	    return $results;

  }
}
