<?php

namespace GG\BoutiqueBundle\Repository;

/**
 * MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends \Doctrine\ORM\EntityRepository
{
	

		public function findBy($tabMail){
			$message = \Swift_Message::newInstance()
			->setSubject($tabMail["sujet"])
			->setFrom($tabMail["email"])
			->setTo("rootsart972@gmail.com")
			->setBody(
	            $this->renderView(
	                'GGBoutiqueBundle:Boutique:contact.html.twig',
	                array('name' => $tabMail["message"])
            	)
        	)
        	->setContentType('text/html')	
        	;

			$this->get('mailer')->send($message);

			 return("mail envoyer");
		}
        
}
