<?php

namespace GG\BoutiqueBundle\Repository;

/**
 * RubriquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriquesRepository extends \Doctrine\ORM\EntityRepository{

	public function findByRubrique($rubrique){
		$qb = $this->createQueryBuilder('a');
		$qb
			->where('a.rubrique = :rubrique')
			->setParameter('rubrique', $rubrique)
		;
	    
		return $qb
		    ->getQuery()
		    ->getResult()
	  ;

	}
}
