<?php

namespace GG\BoutiqueBundle\Repository;

/**
 * StockTempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockTempRepository extends \Doctrine\ORM\EntityRepository
{
}
